apiVersion: v1
kind: Namespace
metadata:
  name: webservers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webservers
  name: nginx-dms
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-dms
  template:
    metadata:
      labels:
        app: nginx-dms
    spec:
      containers:
      - name: nginx-dms
        image: nginx
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        # - name: nginx-dms-cm
        #   mountPath: /etc/nginx
        - name: nginx-dms-vol-1
          mountPath: /var/log/nginx
        - name: nginx-dms-vol-2
          mountPath: /etc/nginx
        - name: nginx-dms-vol-3
          mountPath: /usr/share/nginx/html
      volumes:
      # - name: nginx-dms-cm
      #   configMap:
      #     name: nginx-dms-cm
      - name: nginx-dms-vol-1
        hostPath:
          path: /data/dms/log
      - name: nginx-dms-vol-2
        hostPath:
          path: /data/dms/etc
      - name: nginx-dms-vol-3
        hostPath:
          path: /data/dms/html
---
apiVersion: v1
kind: Service
metadata:
  namespace: webservers
  annotations:
  creationTimestamp: null
  labels:
    app: nginx-dms
  name: nginx-dms-service
spec:
  type: LoadBalancer
  ports:
  - name: "9000"
    port: 9000
    targetPort: 80
  selector:
    app: nginx-dms
status:
  loadBalancer: {}
